[[_main]]
  name = "Support"
  identifier = "support"
  weight = 40
  pre = '<i class="fas fa-fw fa-chevron-circle-down"></i>'
[[_main]]
  name = "Repository"
  identifier = "repository"
  parent = "support"
  url = "https://github.com/razonyang/hugo-theme-bootstrap"
  weight = 1
[[_main]]
  name = "Discussions"
  identifier = "discussions"
  parent = "support"
  url = "https://github.com/razonyang/hugo-theme-bootstrap/discussions/new"
  weight = 2
[[_main]]
  name = "Features Request"
  identifier = "feature-request"
  parent = "support"
  url = "https://github.com/razonyang/hugo-theme-bootstrap/issues/new?template=feature_request.md"
  weight = 3
[[_main]]
  parent = "support"
  weight = 4
  [main.params]
    divider = true

[[_footer]]
  name = "Support"
  identifier = "support"
  weight = 1
[[_footer]]
  name = "Repository"
  identifier = "repository"
  parent = "support"
  url = "https://github.com/razonyang/hugo-theme-bootstrap"
  weight = 1
  pre = '<i class="fab fa-fw fa-github"></i>'
[[_footer]]
  name = "Discussions"
  identifier = "discussions"
  parent = "support"
  url = "https://github.com/razonyang/hugo-theme-bootstrap/discussions/new"
  weight = 2
  pre = '<i class="fas fa-fw fa-comments"></i>'
[[_footer]]
  name = "Features Request"
  identifier = "feature-request"
  parent = "support"
  url = "https://github.com/razonyang/hugo-theme-bootstrap/issues/new?template=feature_request.md"
  weight = 3
[[_footer]]
  name = "Bug Report"
  identifier = "bug-report"
  parent = "support"
  url = "https://github.com/razonyang/hugo-theme-bootstrap/issues/new?template=bug_report.md"
  weight = 4

[[_footer]]
  name = "Docs"
  identifier = "docs"
  weight = 2

[[_footer]]
  name = "Features"
  identifier = "features"
  weight = 3

[[_footer]]
  identifier = "demo"
  name = "Demo"
  weight = 4
[[_footer]]
  identifier = "demo-netlify"
  parent = "demo"
  name = "Netlify"
  weight = 1
  url = "https://hbs.razonyang.com"
[[_footer]]
  identifier = "demo-china"
  parent = "demo"
  name = "China"
  weight = 2
  url = "https://hbs-cn.razonyang.com"
